[package]
name = "memory"
version = "0.1.0"
authors = ["charlolizard <nikitas2209@gmail.com>"]

[dependencies]
bitflags = "1.0"

[dependencies.multiboot]
path = "../multiboot"

[dependencies.stdx]
path = "../stdx"

[dependencies.hardware]
path = "../hardware"